//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentesInmobiliarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentesInmobiliarios()
        {
            this.ComentarioAnuncio = new HashSet<ComentarioAnuncio>();
        }
    
        public int agenteInmobiliarioId { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int sucursalId { get; set; }
    
        public virtual Sucursales Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioAnuncio> ComentarioAnuncio { get; set; }
    }
}
