//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentarioAnuncio
    {
        public int ComentarioId { get; set; }
        public string Comentario { get; set; }
        public int AnuncioPublicitarioId { get; set; }
        public Nullable<int> SuscriptorId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual AgentesInmobiliarios AgentesInmobiliarios { get; set; }
        public virtual Suscriptor Suscriptor { get; set; }
    }
}
