//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inmuebles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inmuebles()
        {
            this.AnuncioPublicitario = new HashSet<AnuncioPublicitario>();
            this.InmuebleComponente = new HashSet<InmuebleComponente>();
            this.InmuebleServicios = new HashSet<InmuebleServicios>();
            this.Multimedia = new HashSet<Multimedia>();
        }
    
        public int inmuebleId { get; set; }
        public string codigoNFC { get; set; }
        public string codigoQR { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> suscriptorId { get; set; }
        public Nullable<int> tipoInmuebleId { get; set; }
        public Nullable<int> estadoInmuebleId { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> direccionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuncioPublicitario> AnuncioPublicitario { get; set; }
        public virtual Direcciones Direcciones { get; set; }
        public virtual EstadoInmuebles EstadoInmuebles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InmuebleComponente> InmuebleComponente { get; set; }
        public virtual Suscriptor Suscriptor { get; set; }
        public virtual TipoInmuebles TipoInmuebles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InmuebleServicios> InmuebleServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multimedia> Multimedia { get; set; }
    }
}
