//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SearchMyHomeDBEntities : DbContext
    {
        public SearchMyHomeDBEntities()
            : base("name=SearchMyHomeDBEntities")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentesInmobiliarios> AgentesInmobiliarios { get; set; }
        public virtual DbSet<AnuncioPublicitario> AnuncioPublicitario { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ComentarioAnuncio> ComentarioAnuncio { get; set; }
        public virtual DbSet<Componentes> Componentes { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<EstadoAnuncioPublicitario> EstadoAnuncioPublicitario { get; set; }
        public virtual DbSet<EstadoInmuebles> EstadoInmuebles { get; set; }
        public virtual DbSet<EstadoSuscripcion> EstadoSuscripcion { get; set; }
        public virtual DbSet<Inmobiliarias> Inmobiliarias { get; set; }
        public virtual DbSet<InmuebleComponente> InmuebleComponente { get; set; }
        public virtual DbSet<Inmuebles> Inmuebles { get; set; }
        public virtual DbSet<InmuebleServicios> InmuebleServicios { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Multimedia> Multimedia { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Periodos> Periodos { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Reunion> Reunion { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<ServiciosInmobiliarios> ServiciosInmobiliarios { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoInmuebleComponentes> TipoInmuebleComponentes { get; set; }
        public virtual DbSet<TipoInmuebles> TipoInmuebles { get; set; }
        public virtual DbSet<TipoMultimedia> TipoMultimedia { get; set; }
        public virtual DbSet<TipoServicios> TipoServicios { get; set; }
        public virtual DbSet<TipoSuscripcion> TipoSuscripcion { get; set; }
        public virtual DbSet<TipoSuscripcionSuscriptor> TipoSuscripcionSuscriptor { get; set; }
        public virtual DbSet<Suscriptor> Suscriptor { get; set; }
    }
}
