//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicios()
        {
            this.InmuebleServicios = new HashSet<InmuebleServicios>();
        }
    
        public int servicioId { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public string nombreProveedor { get; set; }
        public Nullable<int> tipoServicioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InmuebleServicios> InmuebleServicios { get; set; }
        public virtual TipoServicios TipoServicios { get; set; }
    }
}
