//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSuscripcionSuscriptor
    {
        public int tipoSuscripcionSuscriptorId { get; set; }
        public Nullable<int> suscriptorId { get; set; }
        public Nullable<int> tipoSuscripcionId { get; set; }
        public Nullable<System.DateTime> fechaCompra { get; set; }
        public Nullable<System.DateTime> fechaExperacion { get; set; }
        public Nullable<int> estadoSuscripcionId { get; set; }
    
        public virtual EstadoSuscripcion EstadoSuscripcion { get; set; }
        public virtual TipoSuscripcion TipoSuscripcion { get; set; }
        public virtual Suscriptor Suscriptor { get; set; }
    }
}
