//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentesInmobiliarios
    {
        public int agenteInmobiliarioId { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int sucursalId { get; set; }
    
        public virtual Sucursales Sucursales { get; set; }
    }
}
