//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InmuebleServicios
    {
        public int inmuebleServicioId { get; set; }
        public Nullable<int> inmuebleId { get; set; }
        public Nullable<int> servicioId { get; set; }
    
        public virtual Inmuebles Inmuebles { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
