//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reunion
    {
        public int reunionId { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaTermino { get; set; }
        public Nullable<System.TimeSpan> duracion { get; set; }
        public int suscriptorSolicitanteId { get; set; }
        public int suscriptorEncargadoId { get; set; }
        public Nullable<int> estadoReunionId { get; set; }
    
        public virtual Suscriptor Suscriptor { get; set; }
        public virtual Suscriptor Suscriptor1 { get; set; }
    }
}
