//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursales()
        {
            this.AgentesInmobiliarios = new HashSet<AgentesInmobiliarios>();
        }
    
        public int sucursalId { get; set; }
        public Nullable<int> direccionId { get; set; }
        public string numeroTelefonico { get; set; }
        public Nullable<int> inmobiliarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentesInmobiliarios> AgentesInmobiliarios { get; set; }
        public virtual Direcciones Direcciones { get; set; }
        public virtual Inmobiliarias Inmobiliarias { get; set; }
    }
}
