//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchMyHome.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoInmuebleComponentes
    {
        public int tipoInmuebleComponenteId { get; set; }
        public Nullable<int> tipoInmuebleId { get; set; }
        public Nullable<int> componenteId { get; set; }
    
        public virtual Componentes Componentes { get; set; }
        public virtual TipoInmuebles TipoInmuebles { get; set; }
    }
}
